import type {Metadata} from 'next';
import './globals.css';
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: 'Velocity Manager',
  description: 'Manage game servers and backend instances with ease.',
=======

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
>>>>>>> 73da13e (initial scaffold)
=======
import { ThemeProvider } from '@/components/theme-provider';
import { Toaster } from '@/components/ui/toaster';
import {
  SidebarProvider,
  Sidebar,
  SidebarHeader,
  SidebarContent,
  SidebarTrigger,
  SidebarInset,
} from '@/components/ui/sidebar';
import { MainNav } from '@/components/main-nav';
import { Header } from '@/components/header';
import { Icons } from '@/components/icons';

export const metadata: Metadata = {
  title: 'Velocity Manager',
  description: 'Manage your Minecraft servers with ease.',
>>>>>>> 8238499 (Updated app)
=======
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: 'Velocity Manager',
  description: 'Manage game servers and backend instances with ease.',
>>>>>>> e06a37c (vv)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    <html lang="en" className="dark">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        {children}
        <Toaster />
      </body>
=======
    <html lang="en">
=======
    <html lang="en" suppressHydrationWarning>
>>>>>>> 8238499 (Updated app)
=======
    <html lang="en" className="dark">
>>>>>>> e06a37c (vv)
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </head>
<<<<<<< HEAD
      <body className="font-body antialiased">{children}</body>
>>>>>>> 73da13e (initial scaffold)
=======
      <body className="font-body antialiased">
        {children}
        <Toaster />
      </body>
>>>>>>> 8238499 (Updated app)
    </html>
  );
}
