name: SpigotVManager
version: 1.0.0
main: com.velocitymanager.spigot.SpigotVManager
api-version: '1.20'
description: GUI companion for the Velocity Manager plugin.
authors: [VelocityManager]
commands:
  vmanagegui:
    description: Opens the Velocity server management GUI.
    usage: /vmanagegui
    permission: velocitymanager.gui
permissions:
  velocitymanager.gui:
    description: Allows access to the /vmanagegui command.
    default: op
